# GitHub Action
# Builds sphinx documentation and pushes it to gh-pages

name: Documentation

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Install sphinx
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build and deploy docs
      run: bash ci/sphinx-documentation.sh

